### ISSUE TITLE
Nested objects in a nested array - key disapear

### ISSUE THREAD

**Issue by soyuka** [salsify/jsonstreamingparser#24]
To reproduce the behavior, modify `example.json` to :

```
[
  {
    "name": "example document for wicked fast parsing of huge json docs",
    "integer": 123,
    "totally sweet scientific notation": -123.123e-2,
    "unicode? you betcha!": "ú™£¢∞§\u2665",
    "zero character": "0",
    "null is boring": null,
    //this is the important part
    "lines": [
      { "test" : 1, "test2" : 2},
      { "test" : 1, "test2" : 2}
    ]
  },
  ...
]
```

Using the `example.php` script, it'll produce:

```
  [0]=>
  array(7) {
    ...
    [0]=> //this key should be "list" not "0"
    array(2) {
      [0]=>
      array(2) {
        ["test"]=>
        int(1)
        ["test2"]=>
        int(2)
      }
      [1]=>
      array(2) {
        ["test"]=>
        int(1)
        ["test2"]=>
        int(2)
      }
    }
  }
``` 

I first though it was because of the `start_object` method but it's not. 
I've not looked into the core script to see if I could fix this but if someone had a clue on that it'd be great! Is it a bug or is this the indented behavior?

**Comment by soyuka** [comment]
http://soyuka.me/streaming-big-json-files-the-good-way/

@nosweat  My Listener is on the blog post. Feel free to use it.
Here is a [small json test file](https://gist.github.com/soyuka/a1d83ff9ff1a6c5cc269)

@dfreeman Thanks for this nice script, a bit more comments on the main code could be helpful!

**Comment by gonzofy** [comment]
@soyuka I mean to complement you on the blog post a while ago but forgot about it. Great post; thanks for writing! I agree that the code could be better documented and will merge helpful comments from anyone that wants to spend time doing so (right now I'm a bit distracted with other projects to do more than fix bugs).
