### ISSUE TITLE
geoJson example fails on nested array

### ISSUE THREAD

**Issue by Ventzy** [salsify/jsonstreamingparser#27]
Here is example of what json I have

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "id": "adresse_bbr_bydel.68",
      "geometry": { "type": "Point", "coordinates": [12.607440548809672, 55.68879957907828] },
      "geometry_name": "wkb_geometry"
    }
  ]
}

This throws and exception for missing key for the line if ($this->_key[$this->_level]) { in GeoJsonParser for the nested "coordinates" array. It can be easily fixed by replacing it with if (isset($this->_key[$this->_level])) {. After that it works perfectly for my file - when key is missing it goes to the else part, where last object is treated like array and not hash.

**Comment by Pton** [comment]
Fixed in my PR https://github.com/salsify/jsonstreamingparser/pull/45

**Comment by MAXakaWIZARD** [comment]
Corresponding test case has been added.
