### ISSUE TITLE
Lack of namespaces / PSR-4 compliance

### ISSUE THREAD

**Issue by hackel** [salsify/jsonstreamingparser#29]
Please make sure all of your classes have proper namespaces so that they may be safely used in a 3rd-party project. I would highly recommend adhering to the PSR-4 autoloading standard:  http://www.php-fig.org/psr/psr-4/

**Comment by andig** [comment]
@salsify-dev would you accept a PR? I'm failing to use this lib for exactly the same reason.

**Comment by gonzofy** [comment]
@andig I would be happy to accept a PR.

**Comment by andig** [comment]
@gonzofy just found that there is already a working fork at https://github.com/Im0rtality/jsonstreamingparser/ You can create the PR from there yourself ;) I've also submitted further patch for large integers that is waiting for acceptance.

**Comment by gonzofy** [comment]
@andig Thanks for that. @darrenoh put up a PR as you can see, but it brings over a bunch of changes that I don't want to straight up accept.

**Comment by gonzofy** [comment]
@andig I don't see the PR for large integers; is that here or in the fork?

**Comment by andig** [comment]
Its unaccepted in the fork: https://github.com/Im0rtality/jsonstreamingparser/pull/1. Should I reraise against yours?

**Comment by gonzofy** [comment]
Very happy to accept against mine. Thanks!

**Comment by andig** [comment]
See here for the changes https://github.com/Im0rtality/jsonstreamingparser/compare/master...andig:fix
Unfortunately cant push with giving you the rest of the fork, too.

**Comment by gonzofy** [comment]
Closed by PR.

**Comment by andig** [comment]
@gonzofy it's not closed- the bigint issue has not been merged upstream!

See https://github.com/Im0rtality/jsonstreamingparser/compare/master...andig:fix as I cannot push without re-forking.

**Comment by gonzofy** [comment]
@andig the issue with namespaces seems unrelated to the PR you linked to for BigInts unless I'm missing something. I've re-opened for now, but could you be more specific about what's wrong?

**Comment by andig** [comment]
@gonzofy namespaces are fixed, I'll open new issue for bigint, thank you!

**Comment by gonzofy** [comment]
Thanks @andig !!
