### ISSUE TITLE
Goal of Listener ?

### ISSUE THREAD

**Issue by Kraguesh** [salsify/jsonstreamingparser#30]
Hello,

I would try your parser but I don't understand the Listener's goal and I don't know how to do mine.

Thanks

**Comment by soyuka** [comment]
Take a look at : http://soyuka.me/streaming-big-json-files-the-good-way/.

**Comment by Kraguesh** [comment]
Je viens de voir que tu es Français. C'est peut être un poil plus pratique car mon anglais est basique. 
J'ai besoin juste de parser des enormes fichiers JSON en tableau PHP et je suis tombé sur cette lib qui m'a l'air interessante connaissant SAX. 

Je ne comprends juste pas comment implémenter le Listener. Est il en fonction de la structure de mon JSON ou y'a une version générique ?

**Comment by soyuka** [comment]
@all non-french people, sorry about this we'll continue this discussion through emails.

---------

Pas envie de polluer les issues ici, pour continuer la discussion tu peux m'envoyer un mail à soyuka@gmail.com. 

Il faut se dire que si tu veux un tableau depuis un fichier ce n'est pas ce qu'il te faut. Par contre si tu souhaites streamer ton json et effectuer une tâche sur chacun des objets de ce json (indépendamment du reste du fichier) tu peux. 

Le Listener sert à appeler une fonction lorsque tu rencontre un objet, un tableau, une clé etc. Celui présenté sur mon blog est spécifique à une structure du genre :

```
[{obj}, {obj}, {obj}]
```

Grâce à mon listener, la fonction en paramètre du constructeur sera appelée à chaque obj du niveau 1 du tableau. C'est donc spécifique mais finalement c'est une structure commune.

```
$listener = new ObjectListener(function($obj) {
    var_dump($obj);
});

$stream = fopen($testfile, 'r');
$parser = new JsonStreamingParser_Parser($stream, $listener);
$parser->parse();
```

Donc non il n'y a pas de version générique et c'est plutôt propre à ce que tu veux faire avec le fichier et ses objets. A toi de regarder les exemples [là](https://github.com/salsify/jsonstreamingparser/tree/master/example) et de faire ton listener. Tu peux aussi tenter de bidouiller avec le miens [gist](https://gist.github.com/soyuka/4468eab47aceb6abd1bf).

**Comment by sschueller** [comment]
https://gist.github.com/soyuka/4468eab47aceb6abd1bf

**Comment by soyuka** [comment]
This can be closed :).
