### ISSUE TITLE
 Interface 'JsonStreamingParser\Listener' not found

### ISSUE THREAD

**Issue by VAMPIIRE** [salsify/jsonstreamingparser#35]
Hello. I"ve tried to check your example and got this error  "Interface 'JsonStreamingParser\Listener' not found in streamphp\src\JsonStreamingParser\Listener\IdleListener.php on line 8". How can I resolve this issue/

**Comment by gonzofy** [comment]
I'm not sure what you mean by "check my example". How are you trying to run the example?

Look in the tests directory for other examples. All the tests are passing in automation, so they show other working examples of using the interface.

It sounds to me like you're not including the parser files correctly when importing, or your PHP environment is set up in some weird way. Without knowing exactly the command line you tried to run the parser I can't give you any hints.
