### ISSUE TITLE
Error during import of UTF8 files.

### ISSUE THREAD

**Issue by rsanaie** [salsify/jsonstreamingparser#36]
When we import a UTF8 file fread starts with reading the BOM signature for the file and it causes an error in parsing the stream with error **Document must start with object or array.**

I believe the problem is fully answered here and should be a fairly easy fix :smile: 

https://stackoverflow.com/questions/9126423/php-fread-function-returning-extra-charactors-at-the-front-on-utf-8-text-files

Thanks in advance

**Comment by gonzofy** [comment]
I'd be surprised if UTF8 is a problem, since all the documents I've ever used in the partner are UTF8.

Can you paste in the top 10 lines of the JSON document you're trying to parse?

**Comment by rsanaie** [comment]
Hi Rob,

Thanks for the quick reply. Here's the hexdump of the beginning of the file: 

```
0000000: efbb bf5b 0a20 207b 0a20 2020 2022 6964  ...[.  {.    "id
0000010: 223a 2033 372c 0a20 2020 2022 6e61 6d65  ": 37,.    "name
0000020: 223a 2022 4162 6572 6372 6f6d 6269 6520  ": "Abercrombie 
0000030: 4861 7264 7761 7265 2049 6e63 2e22 2c0a  Hardware Inc.",.
```

**Comment by gonzofy** [comment]
@rsanaie I don't mean the byte sequence; I mean the actual characters from the .txt/.json file.

**Comment by rsanaie** [comment]
Hi Rob,

I've attached the entire file.

Cheers
[Vendors.txt](https://github.com/salsify/jsonstreamingparser/files/98034/Vendors.txt)

**Comment by gonzofy** [comment]
@rsanaie sorry for the delay, but the parser is now able to skip the Byte Order Marks for UTF-encoded JSON documents. Release tag is 6.0.1.
