### ISSUE TITLE
Composer question

### ISSUE THREAD

**Issue by gorankrgovic** [salsify/jsonstreamingparser#37]
I know that this is a stupid question, but how to install the JsonStreamingParser via composer? I've tried with  "php-streaming-json-parser": "4.*"  and "JsonStreamingParser" and what not..

**Comment by soyuka** [comment]
I first thought it was Goran Bregović :p. 

I think that `4.0.0` (released march 7) doesn't have the following commit: https://github.com/salsify/jsonstreamingparser/commit/32439b13600581f4279654db2083c56ce8837b10

If you want `psr-4` use `dev-master`:

```
composer require salsify/json-streaming-parser:dev-master
```

You might have to change the minimum-stability.

@gonzofy possible to release a new tag for this?

**Comment by gorankrgovic** [comment]
Oh yes! :) And it's not a Goran Bregovic lol :D, even though he is my countryman :D. He doesn't have this kind of issues - dealing with Json files and such, lucky for him.. :)

**Comment by soyuka** [comment]
ping @gonzofy

**Comment by gonzofy** [comment]
Sorry for the delay @soyuka and @gorankrgovic ; is the solution you want to tag a new release 5.0.0 given the incompatibility with psr-4?

**Comment by soyuka** [comment]
Np! Indeed master works fine with psr-4 but there is no release and we have
to depend on master, which is not very clean.
Would you mind releasing a new tag? Thanks!
Le mar. 1 mars 2016 à 13:15, Rob Gonzalez <notifications@github.com> a
écrit :

**Comment by gonzofy** [comment]
@soyuka done! v5.0 tagged.

**Comment by soyuka** [comment]
<3 thanks!

**Comment by gorankrgovic** [comment]
Thanks guys. I really appreciate it!
