### ISSUE TITLE
Ability to stop parsing from listener

### ISSUE THREAD

**Issue by MAXakaWIZARD** [salsify/jsonstreamingparser#38]
Is there any ability to stop parsing process from listener?

**Comment by soyuka** [comment]
What do you mean stop ?
Le sam. 12 mars 2016 à 21:59, Max Grigorian <notifications@github.com> a
écrit :

**Comment by MAXakaWIZARD** [comment]
@soyuka I mean for example I have very large file and need to stop parsing earlier (process only few items from the start).

**Comment by soyuka** [comment]
You have to implement a listener that allows you to stop after x items. You'll have to handle yourself how to start at the previous and etc. 
IMO, you may not need to implement this as this library ables you to handle objects with a very low memory footprint.

**Comment by MAXakaWIZARD** [comment]
I need this anyway, because file parsing takes 1 min to process all file and I need to break early. And I do not see how this can be done from listener. Maybe I'm missing something.

**Comment by gonzofy** [comment]
Would be a relatively easy change if you want to submit a pull request. You'd just need to add a method to the parser called `stop()` which would set a flag which would cause the `parse()` method to break out of the loop reading characters.

Happy to look at a PR if you want to submit it.

**Comment by MAXakaWIZARD** [comment]
@gonzofy I'm looking forward to make a PR for this. In your proposed solution there must be access to parser instance from inside the listener. But I don't think this is a big deal.

**Comment by gonzofy** [comment]
Exactly. I don't think you can simply stop the parsing without modifying the parser itself since that loop essentially runs the application thread until it's finished parsing the file.

**Comment by MAXakaWIZARD** [comment]
@gonzofy Please review #39
