### ISSUE TITLE
PSR-2 code style

### ISSUE THREAD

**Issue by MAXakaWIZARD** [salsify/jsonstreamingparser#40]
Are there any plans to switch to PSR-2 coding standard?
We can release this under `6.0`.
I can make a PR.

**Comment by gonzofy** [comment]
Always happy to review a PR! Appreciate it @MAXakaWIZARD

**Comment by MAXakaWIZARD** [comment]
And it would be nice to do some cleanup in tests, cause currently it is a mess.

**Comment by gonzofy** [comment]
+1
