### ISSUE TITLE
Feature request: Support for PSR-7

### ISSUE THREAD

**Issue by manuelkiessling** [salsify/jsonstreamingparser#43]
Really like this library, but would love to use it together with GuzzleHttp 6, which provides a very nice streaming API based on PSR-7. However, an HTTP response that is exposed by Guzzle as a stream is not the kind of stream that works with this library.

This would allow to consume large HTTP responses that are send in chunks by the server very efficiently by transforming them into JSON objects via streaming.

See http://docs.guzzlephp.org/en/latest/psr7.html#streams and https://github.com/guzzle/psr7/blob/master/README.md for further details.

**Comment by gonzofy** [comment]
Hi @manuelkiessling - one of the benefits of the SAX/event style of streaming is that the pattern enables you to break down a stream easily into meaningful objects. The general approach you sent is for a general stream (ie characters) which is less useful to people that are specifically streaming something with known structure (ie JSON).

That said, as an alternative interface to the SAX style that we have here, I'd be willing to look at a PR that shows how to integrate it into the approach as an alternative. However, I'm a little skeptical that it leads to better usability.
