### ISSUE TITLE
whitespace at the beginning of the file

### ISSUE THREAD

**Issue by Nexucis** [salsify/jsonstreamingparser#44]
hi,
First, thank you very much for your powerful JSON parser.
After few moments using your parser, i found that a whitespace at the beginning of the file raise an exception (`JStreamingParser line 337 $this->throwParseError("Document must start with object or array."`). 
It was quite annoying in my use case. As an hotfix, I have removed the test : 
` this->state === self::STATE_START_DOCUMENT at line 188 in JStreamingParser`
But I'm not sure this is the best way to fix my problem.
What do you think about that? 

Thanks again for your work.

**Comment by gonzofy** [comment]
Hi @Nexucis -

I'm not sure I follow; what file is causing the problem? Can you submit a PR?

**Comment by Nexucis** [comment]
Hi @gonzofy,

Thanks for replying.
I attached an example file which raised the exception. I hope that you will understand easier what i try to explain.

[upload.zip](https://github.com/salsify/jsonstreamingparser/files/200875/upload.zip)

**Comment by gonzofy** [comment]
Thanks for the example. You're right; I have fixed the problem.
