### ISSUE TITLE
Usage with PSR-7 Psr\Http\Message\StreamInterface?

### ISSUE THREAD

**Issue by JonasRudolph** [salsify/jsonstreamingparser#46]
Hey :)
Is there a way, I could use this parser with an instance of Psr\Http\Message\StreamInterface?
Thanks!

**Comment by gonzofy** [comment]
Hi @JonasRudolph-

See #43 for my response to this. Short answer is that the StreamInterface is not a good interface for the problem this library addresses.

best,
Rob
