### ISSUE TITLE
Overridable bufferer

### ISSUE THREAD

**Issue by rudiedirkx** [salsify/jsonstreamingparser#49]
Currently the bufferer is part of the parser:

```
$line = stream_get_line($this->stream, $this->bufferSize, $this->lineEnding);
```

but that might not be an efficient way to download JSON chars. I'd like to download in 100K chunks no matter the line endings.

In this case, I'd only have to override that 1 line, but maybe more of the file operations could be extensible, like EOF.

**Comment by gonzofy** [comment]
@rudiedirkx makes sense. you could do what you're looking for by downloading into your own buffer and presenting an IO interface to the streaming parser, but if you want to submit a PR to break up the buffering from the parsing, I'd be open to looking at it.

**Comment by rudiedirkx** [comment]
> downloading into your own buffer and presenting an IO interface to the streaming parser

say what..? Can I proxy the buffer process outside of the Parser? Is that a PHP thing..?

I was thinking of a few specific, overridable methods that do just the buffering. Nothing fancy. PR coming.

**Comment by gonzofy** [comment]
This is not a PHP thing; it's a general programming thing. The parser currently is passed a stream in the constructor. You can create your own streaming interface that includes a custom buffer, where your stream reads from the original source, buffers the data, and passes it into the parser.

**Comment by rudiedirkx** [comment]
> create your own streaming interface

I don't know what that means... Parser expects a `resource`. I can't just 'reate my own streamer machine. It really really wants a resource. If I can create a resource that proxies and buffers the real resource, that's a PHP thing, isn't it? But I've never heard of it. Do you mean `stream_wrapper_register()` ?
