### ISSUE TITLE
Add recorder to use json_decode()

### ISSUE THREAD

**Issue by rudiedirkx** [salsify/jsonstreamingparser#51]
If you have a list of 200k objects, which are all small enough to decode with `json_decode()`, it's much faster to combine streaming and decoding: streaming the document flow, decoding single objects. That would require a recorder to remember the bytes to create a json string.

That's probably doable with the current code by overriding `consumeChar()` and `startObject()` etc, but maybe not. I haven't looked into it yet.

Idea? Maybe I'll start hacking and make a merge request.

**Comment by gonzofy** [comment]
I get the use case, but I'd have to see the merge request to see how much of a departure from the current mode of operation this would be, since it feels like a different kind of implementation, but I could be wrong!

**Comment by rudiedirkx** [comment]
It's a combination of streaming and bulk decoding. I've no idea how it would work... I'm trying it out in [my extension](https://github.com/rudiedirkx/jsonpathstreamer) with paths/locations, outside of the core Parser class.

When I have something decent, I'll let you know. It might not be worth the effort.
