### ISSUE TITLE
Breaks if json file doesn't have single root element

### ISSUE THREAD

**Issue by jamestowers** [salsify/jsonstreamingparser#52]
When trying to parse a json file that's doesn't have a single root element you get an `end of document` error:

```
Parsing error in [2:1]. Expected end of document. in /home/vagrant/projects/tracks/vendor/salsify/json-streaming-parser/src/Parser.php:692
```

Doesn't work:

```
{"user_id": "1d30bb024d", "timestamp": "20161001T10:15:00", "device_type": "desktop", "os": "Windows"},
{"user_id": "e3bac2ed46", "timestamp": "20161001T07:15:00", "device_type": "desktop", "os": "Mac"},
{"user_id": "3bac25ed46", "timestamp": "20161001T07:15:00", "device_type": "desktop", "os": "Mac"},
{"user_id": "03e3bacd46", "timestamp": "20161001T07:30:00", "device_type": "desktop", "os": "Mac"}
```

Works:

```
[
    {"user_id": "1d30bb024d", "timestamp": "20161001T10:15:00", "device_type": "desktop", "os": "Windows"},
    {"user_id": "e3bac2ed46", "timestamp": "20161001T07:15:00", "device_type": "desktop", "os": "Mac"},
    {"user_id": "3bac25ed46", "timestamp": "20161001T07:15:00", "device_type": "desktop", "os": "Mac"},
    {"user_id": "03e3bacd46", "timestamp": "20161001T07:30:00", "device_type": "desktop", "os": "Mac"}
]
```

**Comment by peterpp** [comment]
And that's OK. Your JSON is invalid. There can't be multiple objects.

**Comment by jamestowers** [comment]
I was worried that would be the case... That is how i'm getting the data from a third party api call. 

Is there maybe something I can do in `startDocument` method of the listener to get round the issue?

**Comment by dpordomingo** [comment]
I'd expect that if this is an "streaming-parser", calling many times to `$parser->parse();`, I'd receive subsequent jsons;
that way, the new api would be something like the following:

```
$listener = new InMemoryListener();
$stream = fopen('http://www.example.com', 'r');
$parser = new Parser($stream, $listener);
try {
    while ($parser->parse() !== Parser::EOF) {
        var_dump($listener->getJson());
    }
} finally {
    fclose($stream);
}
```

Do you think guys that it would be usefull if I PR this? @gonzofy @jamestowers @peterpp

**Comment by gonzofy** [comment]
@dpordomingo that doesn't make any sense. The whole point of a streaming parser is NOT to return JSON, but rather to return specific elements one-at-a-time so that you don't have to hold the document in memory. Often the document is fetched (like in your example) from the web, and the data is sent through the parser and then discarded afterwards, so that running parse multiple times doesn't make sense.
