### ISSUE TITLE
Parse of 0x7F byte in strings

### ISSUE THREAD

**Issue by mappu** [salsify/jsonstreamingparser#53]
Hi,

I am consuming some third-party JSON which does not escape `\x7F` byte in strings.

[src/Parser.php#L218](https://github.com/salsify/jsonstreamingparser/blob/master/src/Parser.php#L218) does consider this invalid. But i think other libraries do not consider this invalid.

Is there any more information about this issue?

**Comment by gonzofy** [comment]
see http://json.org/ and in particular the string parsing section.

Unicode characters must be escaped from what I read, so the JSON itself is invalid. Can you open it up in e.g. Chrome or another JSON viewer?

**Comment by mappu** [comment]
0x7F is the UTF-8 representation of U+007F DELETE, which is a Control character. According to json.org spec, Control characters should be encoded with \u, in this case as \u007F.

However, the json.org website is only a simplified version of [the ECMA-404 spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf), which states more accurately:

> "the characters that must be escaped: [...] the control characters U+0000 to U+001F"

So it's not including all control characters. 0x7F is exempt.

You can verify the behaviour of some major JSON encoders for 0x7F:

```
$ echo 'console.log(JSON.stringify({dch: "\u007F"}));' | node | xxd
00000000: 7b22 6463 6822 3a22 7f22 7d0a            {"dch":"."}.

$ php -r 'echo json_encode(["dch" => "\x7F"]);' | xxd
00000000: 7b22 6463 6822 3a22 7f22 7d              {"dch":"."}
```

So i think 0x7F should not be considered a control character, it is safe to appear directly within a JSON string and should be decoded correctly.

**Comment by gonzofy** [comment]
well, i stand corrected! thanks @mappu. do you have time to submit a PR? I don't think I'll be able to get to it in the next week or two.

**Comment by e1himself** [comment]
This is fixed in master. 
Can you please tag a new release?
Thanks.

**Comment by gonzofy** [comment]
@e1himself done. v6.0.2.
