### ISSUE TITLE
How to install through the composer?

### ISSUE THREAD

**Issue by Aligan** [salsify/jsonstreamingparser#55]
How to install through the composer?

`
composer require salsify/jsonstreamingparser
`
not working

**Comment by bensbox** [comment]
In total of 10 seconds:
- first 7s -> goto packagist.org -> type jsonstreamingparser
- as a alternative for another 3s -> type into your console composer search jsonstreamingparser

-> `composer require salsify/json-streaming-parser`

;-)

**Comment by dinamic** [comment]
@Aligan feel free to close down this issue if your problem has been resolved.
