### ISSUE TITLE
How to find out that one iteration ended

### ISSUE THREAD

**Issue by multiaki** [salsify/jsonstreamingparser#57]
How to find out that one iteration of json object ended?

for example json string:
[{ ..1.. }, { ..2.. }, { ..3.. }]
Is there any way to know that Obj#1 has ended if the json object is multidimensional?

**Comment by gonzofy** [comment]
Yes, but it's on you to implement in a Listener class of your own creation.

Your Listener implementation has to remember context such as object parsing depth and count. This does add implementation complexity vs. e.g. loading the entire thing in memory, but that's the price you pay for streaming character by character in this way.

**Comment by peterpp** [comment]
@multiaki, try to look at [JsonCollectionParser](https://github.com/MAXakaWIZARD/JsonCollectionParser)
Maybee this is what you need. Or you can just look, how to implement custom Listener.

**Comment by multiaki** [comment]
Now, on the endObject() event, I check whether $key is equal to "<LastValue>". But the Json might change. I wanted to know a better way of knowing that it is the last key.
