### ISSUE TITLE
Add support for a flow of json documents

### ISSUE THREAD

**Issue by OnkelTem** [salsify/jsonstreamingparser#60]
Hi!

Thanks for the parser. I want to enhance it a bit, because while parsing one big json is definitely a good thing to do, it seemed to be not enough for real test cases where streams of whole json documents are quite frequent. Hold on, I'm going to provide a PR.

**Comment by MAXakaWIZARD** [comment]
Requested feature has been released in [v8.0.2](https://github.com/salsify/jsonstreamingparser/releases/tag/v8.0.2)
