### ISSUE TITLE
Provide a useful object reader in "core"

### ISSUE THREAD

**Issue by OnkelTem** [salsify/jsonstreamingparser#62]
Currently **jsonstreamingparser** is not a ready-to-use solution. It provides the following readers (listeners):

* GeoJsonListener.php - reads GeoJSON
* IdleListener.php - reads nothing
* InMemoryListener.php - reads all in memory
* SubsetConsumerListener.php - didn't get what it does as no description was provided.

--- neither of which can be used with a arbitrary JSON data. Maybe that's so because the author didn't find any really useful and generic reader (except for GeoJSON which is certainly not generic)? That could be the case, yeah, and if we look at the project README, we would clearly read the message *simply implement your Listener and it's done!". That easy! 

Is that? Well guys I've tried to implement a so called Listener and I can tell you: IT'S BLOODY DIFFICULT, cumbersome and time consuming. Honestly I don't see any point in implementing something more difficult then just a reader of objects going one after another. Because if you really want to preprocess json, you'd definitely use a specialized tool like [jq](https://stedolan.github.io/jq/).

So yeah, the generic case exists and it's called: **reader of top-level objects**.

By a good fortune it is already implemented here: https://github.com/MAXakaWIZARD/JsonCollectionParser 

My proposition is to include it in the list of "standard" readers (listeners).

Also, let's:
* consider not including its Parser as it doesn't seem to be generic;
* finish the work started here: #60  (add support for a stream of json documents);
* finish the work started [here](https://github.com/MAXakaWIZARD/JsonCollectionParser/issues/3) (the same support for document streams, also objects, objects in subarrays etc)

Let's summon @MAXakaWIZARD for the discussion.

**Comment by gonzofy** [comment]
@OnkelTem agree that having a *reader of top-level objects* is a good idea, and will make implementing a Listener for many use cases much easier.

The Geo Listener I agree doesn't really fit the model here. The In Memory Listener, for what it's worth, was included largely to help with debugging, since the entire point of the streaming parser is that the documents you run through it are, in practice, to large to be loaded into memory.

Many of the largest JSON documents I deal with have only one top-level object with significant nesting in them, or sometimes 4 top-level objects with one of them containing all the real data, so it doesn't fit a lot of what I see out there.

**Comment by gonzofy** [comment]
@tschallacka so you're really just iterating over the objects and dumping them one-at-a-time into the DB. Makes sense. Feel free to submit a new listener class for this use case (you're already most of the way there) and I'll take a look at it.

**Comment by NigelRel3** [comment]
Not sure if this is classed as a 'useful' listener as part of the core, but I've created one based on something similar to the idea of specifying routes in a web API.  The listener is JsonStreamingParser\Listener\RegexListener and there are tests and a short example code to show it it may be used (example/example_regex.php).

A quick idea is that you set a regex of the content your interested in - /1/name, and then a callback which will process the data - function ($data).  So this extracts the second (0 based) element of a JSON array and then the name element, passing this as $data. (The sample data used is tests/data/example.json)

You can also use capture groups in the regex - (.*/name) and the callback is then defined as function ($data, $path).  For this is will pass /0/name and /1/name from the example.json along with the data.

It's in 8.0.1, if anyone finds any bugs or 'interesting; features then let me know and I will investigate.

**Comment by MAXakaWIZARD** [comment]
@gonzofy I think this issue can be closed
