### ISSUE TITLE
End of stream

### ISSUE THREAD

**Issue by flightltd** [salsify/jsonstreamingparser#79]
Hi,

I've implemented a database load using the GeoJsonListener which works well but at the moment I'm creating an insert for each item. The source files are large (3gb +)  and so I'd like to amend the code to create bulk loading INSERTs with up to five hundred items each. Can you tell me how I can signal that the stream has ended so that I can wrap up the last insert?

Cheers.

**Comment by flightltd** [comment]
Well, asking the question normally leads to one getting the answer - execute the final statement (if there is one) after the fclose I suppose? Thanks anyway.

**Comment by gonzofy** [comment]
You're looking for `endDocument()` when implementing a Listener.

**Comment by flightltd** [comment]
Thank you.
