### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by MAXakaWIZARD** [salsify/jsonstreamingparser#82]
Latest version 8.0.1 is broken.
Please release new one, which will include at least this PR: https://github.com/salsify/jsonstreamingparser/pull/76

**Comment by MAXakaWIZARD** [comment]
@gonzofy v8.0.2 has been created, but still not available on Packagist: https://packagist.org/packages/salsify/json-streaming-parser
Probably Github hook should be updated: https://packagist.org/about#how-to-update-packages

**Comment by gonzofy** [comment]
@MAXakaWIZARD I don't have a packagist account and wasn't responsible for getting the project up there in the first place. When I go to log in with GitHub it asks for permissions that I'm unable to agree to. If there's any way for anyone else to simply have packagist pull from this public repository to update the revision I'd prefer that than to have to maintain it personally.

**Comment by MAXakaWIZARD** [comment]
@gonzofy if you are not comfortable logging in into Packagist using Github account, you can add me as a maintainer of this package, so I will be able to set up auto-update for this project on Packagist.

**Comment by gonzofy** [comment]
@MAXakaWIZARD done

**Comment by MAXakaWIZARD** [comment]
@gonzofy it turns out I am still unable to setup webhook on Packagist.
I have contacted Packagist support and they are suggesting you to follow instructions in section **Do not want to log in via GitHub and grant us webhook configuration access?** here: https://packagist.org/about#how-to-update-packages

**Comment by MAXakaWIZARD** [comment]
@gonzofy or you can add me as a maintainer on Packagist 
<img width="1170" alt="Screenshot 2019-10-11 22 02 52" src="https://user-images.githubusercontent.com/1138453/66677741-002f3a00-ec73-11e9-8753-ca55f77c0e9c.png">

**Comment by gonzofy** [comment]
@MAXakaWIZARD push webhook set up. You've got write access to the repo; if you try pushing it should trigger packagist update.

**Comment by MAXakaWIZARD** [comment]
@gonzofy many thanks, sir

**Comment by MAXakaWIZARD** [comment]
v8.0.2 made possible to release v1.6.0 of MAXakaWIZARD/JsonCollectionParser which introduces support for documents flow: https://github.com/MAXakaWIZARD/JsonCollectionParser/blob/master/CHANGELOG.md
