### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by zlatkoverk** [salsify/jsonstreamingparser#96]
Please release new version which includes this change https://github.com/salsify/jsonstreamingparser/pull/95

**Comment by taka-oyama** [comment]
Hi @gonzofy, 

Would it be possible to release v8.3.0 which includes #95 and #97 so we can easily download this via composer? 

Thank you. 🙏🏻

**Comment by gonzofy** [comment]
done

**Comment by taka-oyama** [comment]
Thank you!
