### ISSUE TITLE
String value "0" gets converted to a float 0.0 while using the parser v8.3.0

### ISSUE THREAD

**Issue by DieWallSoCom** [salsify/jsonstreamingparser#98]
Hi,

today I updated the jsonstreamimporter to version 8.3.0 and now the parser is converting the string number "0" to a float _0.0_.

I found a bug in the file ParserHelper.php on the line 50.

```php
...
public static function convertToNumber(string $text)
    {
        // thanks to #andig for the fix for big integers
        if (filter_var($text, FILTER_VALIDATE_INT) && (float) $text === (float) ((int) $text)) {
            // natural number PHP_INT_MIN < $num < PHP_INT_MAX
            return (int) $text;
        }

        // real number or natural number outside PHP_INT_MIN ... PHP_INT_MAX
        return (float) $text;
    }
```

The php function _filter_var_ returns a _0_ for _filter_var($text, FILTER_VALIDATE_INT)_ if $text is "0", so that the if-condition evaluates to false.

It should be fixed to

```php
...
   if (filter_var($text, FILTER_VALIDATE_INT) !== false && (float) $text === (float) ((int) $text)) {
...
```

so that "0" will be correctly parsed to the integer _0_.

**Comment by gonzofy** [comment]
Thank you!
